# Generated by Django 5.2.6 on 2025-09-04 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('descripcion', models.TextField(verbose_name='Descripción completa')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('precio_mayor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio al por mayor')),
                ('cantidad_minima_mayor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad mínima para precio mayor')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de oferta')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Cantidad en stock')),
                ('es_activo', models.BooleanField(default=True, verbose_name='¿Está activo en la tienda?')),
                ('es_destacado', models.BooleanField(default=False, verbose_name='¿Es un producto destacado?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='api.categoria', verbose_name='Categoría')),
                ('materiales', models.ManyToManyField(blank=True, related_name='productos', to='api.material', verbose_name='Materiales')),
                ('proveedores', models.ManyToManyField(blank=True, related_name='productos', to='api.proveedor', verbose_name='Proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='Archivo de imagen')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es la imagen principal?')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.producto', verbose_name='Producto')),
            ],
        ),
    ]
