# Generated by Django 5.2.6 on 2025-09-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedores',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
