# Generated by Django 5.2.6 on 2025-09-18 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_direccion_carrito_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total de la compra')),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('whatsapp', 'WhatsApp')], default='whatsapp', max_length=50, verbose_name='Método de pago')),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50, verbose_name='Estado del pago')),
                ('estado_orden', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=50, verbose_name='Estado de la orden')),
                ('cantidad_compra', models.PositiveIntegerField(verbose_name='Total de productos en la orden')),
                ('comprobante_envio', models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Imagen del comprobante de envío')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='api.direccion', verbose_name='Dirección de envío')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad comprada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario al comprar')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total por este item')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.orden', verbose_name='Orden')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.producto', verbose_name='Producto')),
            ],
        ),
    ]
