# Generated by Django 5.2.6 on 2025-09-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orden_ordenitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente_comprobante', 'Pendiente de Comprobante'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente_comprobante', max_length=50, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('yape', 'Yape')], default='transferencia', max_length=50, verbose_name='Método de pago'),
        ),
    ]
