# Generated by Django 5.2.6 on 2025-10-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_orden_estado_pago_alter_orden_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='numero_orden',
            field=models.CharField(default='temp', editable=False, max_length=20, unique=True, verbose_name='Número de Orden'),
            preserve_default=False,
        ),
    ]
