# Generated by Django 5.2.6 on 2025-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orden_numero_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False, verbose_name='¿Recordatorio de pago enviado?'),
        ),
    ]
