# Generated by Django 5.2.6 on 2025-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orden_recordatorio_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes_pago/', verbose_name='Imagen del comprobante de PAGO'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='comprobante_envio',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes_envio/', verbose_name='Imagen del comprobante de ENVÍO'),
        ),
    ]
