# Generated by Django 5.2.6 on 2025-11-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_orden_comprobante_pago_alter_orden_comprobante_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='mercado_pago_payment_id',
            field=models.CharField(blank=True, help_text='ID del pago confirmado por Mercado Pago', max_length=100, null=True, verbose_name='ID de Pago de Mercado Pago'),
        ),
        migrations.AddField(
            model_name='orden',
            name='mercado_pago_preference_id',
            field=models.CharField(blank=True, help_text='ID de la preferencia de pago creada en Mercado Pago', max_length=100, null=True, verbose_name='ID de Preferencia de Mercado Pago'),
        ),
        migrations.AddField(
            model_name='orden',
            name='mercado_pago_status',
            field=models.CharField(blank=True, help_text='Estado del pago según Mercado Pago (approved, pending, rejected, etc.)', max_length=50, null=True, verbose_name='Estado en Mercado Pago'),
        ),
        migrations.AddField(
            model_name='orden',
            name='mercado_pago_status_detail',
            field=models.CharField(blank=True, help_text='Información adicional sobre el estado del pago', max_length=100, null=True, verbose_name='Detalle del estado MP'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('rechazado', 'Pago Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('yape', 'Yape'), ('mercado_pago', 'Mercado Pago')], default='transferencia', max_length=50, verbose_name='Método de pago'),
        ),
    ]
