# Generated by Django 5.2.6 on 2025-11-16 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_orden_mercado_pago_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.orden')),
            ],
            options={
                'verbose_name': 'Pago Procesado',
                'verbose_name_plural': 'Pagos Procesados',
                'db_table': 'api_payment_processed',
            },
        ),
    ]
