# Generated by Django 5.2.6 on 2026-05-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_direccion_latitud_direccion_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Longitud'),
        ),
    ]
