# Generated by Django 5.2.6 on 2026-06-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_direccion_latitud_alter_direccion_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='Snapshot de la dirección al momento de la compra'),
        ),
    ]
