# Generated by Django 5.2.6 on 2026-08-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_orden_direccion_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='motivo_rechazo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo del rechazo'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('en_revision', 'En Revisión'), ('pagado', 'Pagado'), ('rechazado', 'Pago Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50, verbose_name='Estado del pago'),
        ),
    ]
